/**
 * drift.test.js — Phase D drift guard, step 2 of 2.
 *
 * Loads golden_features.json (generated by generate_golden_cases.py from
 * train_risk_model.py's compute_features()) and recomputes the same cases
 * using the production Lambda's computeFeatures() from
 * infra/lambda/predictAttendanceRisk/index.js. Asserts they agree exactly.
 *
 * If someone changes the feature logic in one language without updating
 * the other, this test fails -- that's the whole point. There is no
 * shared source of truth between the Python training script and the JS
 * Lambda (a deliberate deployment-simplicity tradeoff, see index.js
 * header comment), so this is the only thing standing between a change
 * and silent prediction drift.
 *
 * IMPORTANT: golden_features.json stores Title-case statuses ("Present",
 * "Absent", "Late") because that's what the Python script reads from the
 * raw CSV. This test translates them to uppercase before feeding them to
 * the JS function, because that's what the JS function actually receives
 * from DynamoDB in production. See the isAttended() comments in both
 * index.js and train_risk_model.py for why the casing differs.
 *
 * Regenerate golden_features.json (python generate_golden_cases.py)
 * whenever compute_features() changes in train_risk_model.py, then re-run
 * this test to confirm index.js was updated to match.
 *
 * Run: npx jest drift.test.js
 */

const fs = require('fs');
const path = require('path');

// index.js doesn't export computeFeatures directly (only exports.handler),
// so we require the file's internals via a small re-implementation-free
// extraction: read the file, eval its computeFeatures function in isolation.
// This avoids maintaining a second copy of the function just for testing,
// while not requiring index.js to change its export shape for production.
function loadComputeFeaturesFromLambda() {
  const indexPath = path.join(__dirname, '..', '..', 'lambda', 'predictAttendanceRisk', 'index.js');
  const source = fs.readFileSync(indexPath, 'utf-8');

  // Extract just the isAttended and computeFeatures function bodies and
  // eval them in an isolated scope. Fragile-looking, but deliberately so --
  // this only works if index.js keeps these as plain named functions,
  // which forces anyone changing that structure to also look at this test.
  const sandbox = {};
  // eslint-disable-next-line no-new-func
  const fn = new Function(
    'sandbox',
    source
      .replace(/^const \{[^}]*\} = require\(.*\);$/gm, '') // strip whole require-destructure lines
      .replace(/^const model = require\(.*\);$/gm, '') // strip whole model.json load line
      .replace(/^const client = new DynamoDBClient\(.*\);$/gm, '') // strip DynamoDB client construction
      .replace(/^const doc = DynamoDBDocumentClient\.from\(.*\);$/gm, '') // strip doc client construction
      .replace(/^const ATTENDANCE_TABLE = .*;$/gm, '') // strip env var read (unused by pure functions)
      .replace(/exports\.handler[\s\S]*$/m, '') // strip everything from exports.handler onward
      + '\nsandbox.isAttended = isAttended; sandbox.computeFeatures = computeFeatures;'
  );
  fn(sandbox);
  return sandbox.computeFeatures;
}

const computeFeatures = loadComputeFeaturesFromLambda();

const TITLE_TO_UPPER = { Present: 'PRESENT', Absent: 'ABSENT', Late: 'LATE' };

function toJsRecords(statuses) {
  return statuses.map((s, i) => ({
    date: `2026-05-${String(i + 1).padStart(2, '0')}`,
    status: TITLE_TO_UPPER[s],
  }));
}

describe('feature computation matches between Python training script and JS Lambda', () => {
  const goldenPath = path.join(__dirname, 'golden_features.json');

  if (!fs.existsSync(goldenPath)) {
    test('golden_features.json exists (run generate_golden_cases.py first)', () => {
      throw new Error(
        `${goldenPath} not found. Run: python generate_golden_cases.py`
      );
    });
    return;
  }

  const golden = JSON.parse(fs.readFileSync(goldenPath, 'utf-8'));

  for (const [caseName, { input_statuses, expected_features }] of Object.entries(golden)) {
    test(`case: ${caseName}`, () => {
      const jsRecords = toJsRecords(input_statuses);
      const jsFeatures = computeFeatures(jsRecords);

      expect(jsFeatures).not.toBeNull();

      for (const [key, expectedValue] of Object.entries(expected_features)) {
        // Floating point: Python and JS float arithmetic can differ in the
        // last bit or two even for identical logic. 1e-9 is far tighter
        // than any real discrepancy in feature logic would produce.
        expect(jsFeatures[key]).toBeCloseTo(expectedValue, 9);
      }
    });
  }
});