/**
 * storageQuotaManager.ts
 *
 * Sprint 1 deliverable (Marlyn): local storage compression + 50MB quota
 * manager with 30-day cleanup, sitting alongside Amplify DataStore's own
 * IndexedDB storage.
 *
 * DataStore stores records in IndexedDB automatically — this module doesn't
 * replace that, it *monitors and prunes* it, since DataStore itself has no
 * built-in storage cap or automatic old-record cleanup. Left unmanaged, a
 * device used daily for months would accumulate attendance history
 * indefinitely, risking hitting browser storage limits (which vary by
 * device — often 50MB-a few hundred MB on low-end Android devices/older
 * browsers, per the roadmap's "rural, low-resource" constraint).
 */

import { DataStore } from 'aws-amplify/datastore';
import { AttendanceRecord } from '../models'; // generated by `amplify codegen models`

const QUOTA_LIMIT_BYTES = 50 * 1024 * 1024; // 50MB, per roadmap Sprint 1 target
const RETENTION_DAYS = 30;
const WARN_THRESHOLD_RATIO = 0.8; // warn UI at 80% of quota, before hard cleanup

export interface StorageStatus {
  usedBytes: number;
  quotaBytes: number;
  usedRatio: number;
  approachingLimit: boolean;
}

/**
 * Estimates current storage usage via the browser's Storage API.
 * Falls back gracefully on browsers/devices that don't support estimate().
 */
export async function getStorageStatus(): Promise<StorageStatus> {
  if (!('storage' in navigator) || !('estimate' in navigator.storage)) {
    // Older/low-end browsers may not support this API — fail safe rather
    // than crash, and let the caller decide how to handle "unknown".
    return {
      usedBytes: -1,
      quotaBytes: QUOTA_LIMIT_BYTES,
      usedRatio: -1,
      approachingLimit: false,
    };
  }

  const estimate = await navigator.storage.estimate();
  const usedBytes = estimate.usage ?? 0;
  const usedRatio = usedBytes / QUOTA_LIMIT_BYTES;

  return {
    usedBytes,
    quotaBytes: QUOTA_LIMIT_BYTES,
    usedRatio,
    approachingLimit: usedRatio >= WARN_THRESHOLD_RATIO,
  };
}

/**
 * Approximate per-record size, used for the ~3KB/record budget mentioned in
 * the roadmap. This is intentionally simple (JSON string byte length) rather
 * than true compression — DataStore's own IndexedDB storage isn't something
 * we can compress at the individual-record level without replacing its
 * storage adapter, which is out of scope for Sprint 1. What we *can* control
 * is keeping each record's field set minimal (see AttendanceRecord schema —
 * no redundant denormalized fields) and pruning aggressively via retention.
 */
export function estimateRecordSizeBytes(record: unknown): number {
  return new TextEncoder().encode(JSON.stringify(record)).length;
}

/**
 * Deletes locally-cached AttendanceRecords older than RETENTION_DAYS that
 * have already synced (sync_version confirms a server round-trip happened —
 * never delete anything still pending sync, offline-queued data must survive
 * this cleanup regardless of age).
 */
export async function pruneOldSyncedRecords(): Promise<{ deletedCount: number }> {
  const cutoff = new Date();
  cutoff.setDate(cutoff.getDate() - RETENTION_DAYS);
  const cutoffDateString = cutoff.toISOString().split('T')[0]; // AWSDate format

  const allRecords = await DataStore.query(AttendanceRecord);

  const staleRecords = allRecords.filter((record) => {
    const isOldEnough = record.date < cutoffDateString;
    const isSynced = record.sync_version !== undefined && record.sync_version !== null;
    return isOldEnough && isSynced;
  });

  for (const record of staleRecords) {
    await DataStore.delete(record);
  }

  return { deletedCount: staleRecords.length };
}

/**
 * Call this on app startup and periodically (e.g. once per day, or on each
 * successful sync) — checks quota, prunes if needed, and returns status for
 * the sync-status UI Sasha is building to display.
 */
export async function runStorageMaintenance(): Promise<StorageStatus> {
  let status = await getStorageStatus();

  if (status.approachingLimit) {
    await pruneOldSyncedRecords();
    status = await getStorageStatus(); // re-check after pruning
  }

  return status;
}
